baseURL = "https://www.thorvald.com/prints"
languageCode = "en-us"
title = "Thorvald A. Sanchez"
tags = ["portfolio", "web design", "blog"]
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = "tomanistor"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
  tagline = ""
  author = "Thorvald Sanchez"
  description = "Minimalist Cuban Artist"
  logoBig = "/images/osprey-logo.png"
  logoSmall = "/images/osprey-logo.png"
  favicon = "favicon.ico"
  opengraphImage = "/images/osprey.png"
  email = "thorvaldsanchez@gmail.com"
  googleTagManger = ""
  customCSS = true

  # Social media links in footer
  twitter = "ThorvaldArt"
  linkedin = ""
  github = "futuresarcade"
  facebook = "ThorvaldArt"

  # Copyright and theme author credit in footer
  copyright = true
  credit = false

  # Cache busting of static resources (additional set up required)
  cacheBustCSS = false
  cacheBustJS = false

  # Code highlighting with highlight.js
  highlightJS = true
  highlightJSStyle = "" # For custom highlight.js styles, add your /path/to/styles/default.css
  highlightJSScript = "" # For custom highlight.js languages config, add your /path/to/highlight.pack.js

  # Choose either Formspree contact form or Basin contact form
  ajaxFormspree = false
  ajaxFormspreeGold = false
  ajaxBasin = "https://usebasin.com/f/c6a114cb2e67"

  # Lazy loading with lazysizes
  lazyloading = true

[[menu.main]]
  name = "Work"
  url  = "/#work"
  weight = 1
